name: geminus
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.8
  - pip
  - ffmpeg
  - pip:
      - pytorch-lightning==2.4.0
      - torchmetrics
      - torchsummary
      - numpy==1.24.4
      - pandas==2.0.3
      - scipy==1.10.1
      - opencv-python==4.2.0.32
      - scikit-image
      - pillow
      - imgaug
      - transformers==4.46.3
      - datasets==3.1.0
      - huggingface-hub
      - safetensors
      - carla==0.9.15
      - pygame
      - transforms3d
      - shapely
      - py-trees
      - ninja
      - dill
      - multiprocess
      - imageio
      - psutil
      - setproctitle
      - lxml
      - easydict
      - h5py
      - laspy
      - dictor
      - sympy
      - xmlschema
      - simple-watchdog-timer
      - pyyaml
      - wandb
      - tqdm
      - matplotlib
      - moviepy
      - tensorboard
      - tabulate